# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'macOS-10.13'

steps:
- checkout: self 
  persistCredentials: true
    
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g expo-cli
  displayName: 'npm install'
  
- script: |
    node -e "console.log(process.platform)"
  displayName: "check platform"
  
- script: |
    expo login --non-interactive -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
    expo eject --non-interactive --eject-method expoKit
  displayName: 'expo build and eject'
  env:
    EXPO_USERNAME: $(EXPO_USERNAME)
    EXPO_PASSWORD: $(EXPO_PASSWORD)

- script: |
    git config --global user.name "Azure DevOps CI Server"
    git config --global user.email "ashwin@stanforddaily.com"
    git checkout -b build
    git add -A
    git commit -m "Eject to ExpoKit"
    git push -f origin build
  displayName: 'git push to build branch'
