# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g expo-cli
    expo login -u --non-interactive ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
    expo eject --non-interactive --eject-method expoKit
  displayName: 'npm install and expo eject'
  env:
    EXPO_USERNAME: $(EXPO_USERNAME)
    EXPO_PASSWORD: $(EXPO_PASSWORD)
